### ISSUE TITLE
Poor Reproduction performance

### ISSUE THREAD

**Issue by Anthonyyouny** [ymzhang01/focops#2] opened 2021-11-25 04:29 UTC
Hi,
I am reproducing the code on the example you given. (Humanoid task in the robots with speed limits experiments (using the default parameters)).
However, the performance is really bad. I have compared the hyper-parameters with the list in the paper. I am wondering if I missed something important? What can be reason for that?

**Comment by ymzhang01** [comment] 2021-12-09 07:02
Thank you so much for alerting us of the issue and further email correspondence. We have identified a bug that was inadvertently introduced into the data generator while attempting to optimize that part of the code, the issue is now fixed.

**Closed as completed by ymzhang01** 2021-12-09 07:02 UTC
